name: "install stripe mock"
description: "install stripe mock"
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
    - run: |      
        go install github.com/stripe/stripe-mock@latest
        stripe-mock &
      shell: bash
